### ISSUE TITLE
hacktoberfest 2023

### ISSUE THREAD

**Issue by micalevisk** [darraghoriordan/eslint-plugin-nestjs-typed#108]
can you please participate on Hacktoberfest 2023? I'm looking for nestjs-related repos that I could contribute to on October.

You just need to add the `hacktoberfest` topic to this repository

thanks anyway!

**Comment by NidhiSingh26** [comment]
Hi Micalevish,

I want to contribute on your repository

**Comment by darraghoriordan** [comment]
hmmm OK, I added the topic.

but i'm wary of spam, will remove if there are spammy PRs
