### ISSUE TITLE
New Rule Suggestion: disallow multiple usage of the same 'discoverable' decorator

### ISSUE THREAD

**Issue by micalevisk** [darraghoriordan/eslint-plugin-nestjs-typed#111]
since `@nestjs/core` v10.2.0 we can use the `DiscoveryService.createDecorator` to create type-safe decorators

but we shouldn't be using them multiple times like this:

![image](https://github.com/darraghoriordan/eslint-plugin-nestjs-typed/assets/13461315/337f90e8-6052-482d-92fb-bb73708cfba7)

I'm not sure if this is feasbile to achieve as a lint rule.

---

sample code: https://stackblitz.com/edit/nestjs-discovery-service-issue-bt5oae

**Comment by darraghoriordan** [comment]
Yea nice, this could be a rule. It could even be configurable because most of the decorators from nest/core likely shouldnt be applied twice.

**Comment by micalevisk** [comment]
@darraghoriordan good ideia

are you 100% sure that something like that is possible to have as a rule? I'm not familiar with ESLint rules but I can give it a try

**Comment by darraghoriordan** [comment]
Hey I added this rule. You can read the docs to see how you would configure it with your own list of decorators like "DiscoverDecorator".
