### ISSUE TITLE
add rule to disalow using `@Inject()` without some token when using it on `constructor`

### ISSUE THREAD

**Issue by micalevisk** [darraghoriordan/eslint-plugin-nestjs-typed#116]
The usage of `@Inject()` without some provider's token on parameters is invalid (due to TS limitations, AFIAK). And I didn't succeded on making it fail at build time. So, as of now, we will see a 'dependency not found' error at runtime. This could confuse people.

My suggestion is adding a rule to forbids such usage

![image](https://github.com/darraghoriordan/eslint-plugin-nestjs-typed/assets/13461315/abcf1658-4fa9-4a56-9f7c-aac360eafca6)

<details open>
<summary>code</summary>

```ts
import { Module, Inject, forwardRef } from '@nestjs/common';

class FooService {}

@Module({
  providers: [FooService]
})
export class AppModule {
  @Inject(forwardRef(() => FooService))
  public readonly service: FooService;

  @Inject() private readonly validInjectUsage: FooService

  constructor(
    /*
    @Inject(forwardRef(() => FooService)) private valid: FooService
    ,
    @Inject(undefined) private valid2: FooService
    ,
    @Inject('') private valid3: FooService
    // ,
    */
    @Inject() private invalid: FooService // <<< this should error out as 'you must pass a token'
  ) {}
}
```

</details>

**Comment by darraghoriordan** [comment]
oh interesting. nice suggestion. i'll try to do this sometime this year if i get time 👍 

just thinking (i havent tested) - but is this maybe an esmodule import / export issue ? I know es modules a bit weird about declaring multiple classes in one file and circular references sometimes

**Comment by micalevisk** [comment]
but the final code (after tsc compilation) will be in CJS, not in ESM

and I tried with classes declared in separated files as well. I don't think this is a circular related issue

**Comment by micalevisk** [comment]
This is supported on Nestjs now
