### ISSUE TITLE
Can't install the latest version

### ISSUE THREAD

**Issue by alxamarin** [darraghoriordan/eslint-plugin-nestjs-typed#13]
Getting:
>Found: @typescript-eslint/parser@5.3.1
npm ERR! node_modules/@typescript-eslint/parser
npm ERR!   dev @typescript-eslint/parser@"^5.3.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @typescript-eslint/parser@"5.1.0" from @darraghor/eslint-plugin-nestjs-typed@3.5.3
npm ERR! node_modules/@darraghor/eslint-plugin-nestjs-typed
npm ERR!   dev @darraghor/eslint-plugin-nestjs-typed@"*" from the root project

**Comment by darraghoriordan** [comment]
Hey I made the peer deps more flexibe so the should work with any version of ts-eslint parser >=5.0.0

it should work for you now. I tested in a project with latest parser and it seems to work ok. 

let me know if it's still not working anyway

**Comment by darraghoriordan** [comment]
fixed in 3.5.4
