### ISSUE TITLE
How to configure in microservice project looks for src/**/*.ts

### ISSUE THREAD

**Issue by designscripting** [darraghoriordan/eslint-plugin-nestjs-typed#157]
I am trying to configure in microservice nest js app, and it is throwing below error
Error:
Oops! Something went wrong! :(

ESLint: 8.57.0

No files matching the pattern "src/**/*.ts" were found.
Please check for typing mistakes in the pattern.

Possibly, it should look in "app/**/*.ts" or "./**/*.ts"
Any suggestions

**Comment by AaronMBMorse** [comment]
I'm experiencing the same issue

**Comment by darraghoriordan** [comment]
hey, i describe how to configure this rule, and how to turn off this rule if it doesn't work for you project in the documentation.
