### ISSUE TITLE
Is the `api-method-should-specify-api-response` rule in the recommended config or not?

### ISSUE THREAD

**Issue by ChrisMBarr** [darraghoriordan/eslint-plugin-nestjs-typed#186]
The code seems to specify that this rule is enabled in the recommended config here: https://github.com/darraghoriordan/eslint-plugin-nestjs-typed/blob/077150ce811be7141ba6a191bce74b565b53104f/src/configs/recommended.ts#L16-L17

But the README file seems to specify the opposite: https://github.com/darraghoriordan/eslint-plugin-nestjs-typed/blob/main/README.md?plain=1#L33

**Comment by darraghoriordan** [comment]
yes, if you can submit a PR to update the readme file that would be great 👍
