### ISSUE TITLE
README and package.json updates

### ISSUE THREAD

**Issue by jozefvodicka** [darraghoriordan/eslint-plugin-nestjs-typed#204]
Thank you for this package!

**Few suggestions:**
1. This one is missing and linked in README:
[Hi! I have an idea for a rule...](https://github.com/darraghoriordan/eslint-plugin-nestjs-typed/blob/HEAD/src/docs/rules/should-specify-forbid-unknown-values.md)

2. This one is not present in latest version (5.0.16) of the package https://github.com/darraghoriordan/eslint-plugin-nestjs-typed/blob/15c89ce81632f0340270518ecaf8eab298a0cfad/src/docs/rules/validation-pipe-should-use-forbid-unknown.md

3. In README you refer to "@darraghor/nestjs-typed" but the name of the plugin is "@darraghor/eslint-plugin-nestjs-typed"

4. Is it possible to update in package.json
- all "@typescript-eslint/*" versions to "7.14.1 || ^8.0.0"
- "eslint": "8.57.0 || ˆ9.0.0",

**Comment by darraghoriordan** [comment]
it would be awesome if you could submit PRs to fix some of these

**Comment by jozefvodicka** [comment]
https://github.com/darraghoriordan/eslint-plugin-nestjs-typed/pull/208
