### ISSUE TITLE
Rule to sort modules alphabetically

### ISSUE THREAD

**Issue by robertohein** [darraghoriordan/eslint-plugin-nestjs-typed#28]
Something like this: https://github.com/angular-eslint/angular-eslint/blob/master/packages/eslint-plugin/docs/rules/sort-ngmodule-metadata-arrays.md

Very good package, i was going to create something like this for nestjs but found your package! I'll try to colaborate soon, i have a lot of good nestjs rule ideas

**Comment by robertohein** [comment]
If you have interest i can develop that rule :)

**Comment by darraghoriordan** [comment]
Hey, yea for sure, please add a PR if you get a chance to work on this 👍

**Comment by imranbarbhuiya** [comment]
I'm looking for this rule. Was it implemented?
