### ISSUE TITLE
Swagger, when I add `enumName`  to ApiProperty options, description not display in Swagger UI 

### ISSUE THREAD

**Issue by its-monotype** [darraghoriordan/eslint-plugin-nestjs-typed#46]
```ts
 @ApiProperty({
    enum: BotStatusEnum,
    enumName: 'BotStatusEnum',
    name: 'status',
    description: `
    Current status of the bot:
    * '${BotStatusEnum.ComingSoon}' - Bot will be available soon (in development)
    * '${BotStatusEnum.Working}' - Bot is functional and available for use
    * '${BotStatusEnum.Updating}' - Bot is currently being updated`,
  })
  @Column({
    type: 'enum',
    enum: BotStatusEnum,
  })
  status: BotStatusEnum;
```
![image](https://user-images.githubusercontent.com/79363260/213474229-5c0eaee9-0444-462b-b1aa-a2f8a9cba9f0.png)

If I remove `enumName`, then I can see the description:

![image](https://user-images.githubusercontent.com/79363260/213474510-7c62faf1-80f2-42ea-8557-5de0a3fdccf8.png)

**Comment by darraghoriordan** [comment]
Hey, This is probably something to raise in the https://github.com/nestjs/swagger repository. I don't think this package is causing this issue

Is there something that makes you think this is caused by the eslint rule?

**Comment by its-monotype** [comment]
Not really, but it is strange behaviour that I do not understand because it's suggested to set enumName explicitly but If I do it the description for the enum can't be displayed

**Comment by darraghoriordan** [comment]
Yea ok. I'm not going to be able to change the underlying behaviour of the nest swagger library so if you need to use descriptions you can turn off this rule in your eslint configuration so you can skip setting an enumName.

```
   rules: {
   "@darraghor/nestjs-typed/api-enum-property-best-practices":
            "off",
   }
```
