### ISSUE TITLE
Add custom decorators to api-method-should-specify-api-response

### ISSUE THREAD

**Issue by elliotaplant** [darraghoriordan/eslint-plugin-nestjs-typed#47]
We use this lint rule to ensure all of our API methods define their response types. We also have an additional decorator we want the linter to recognize: `@ApiPaginatedResponse(SomeDataType)` that defines a paginated response of some data type. What do you think about adding some way to include custom decorators in this linter?

**Comment by darraghoriordan** [comment]
Hey, yup this sounds good. there are a couple of examples of rule configurations that accept an array of custom decorators if anyone wants to take a crack at a PR 👍 

I'll keep custom decorator requirement in mind the next time there is a new rule added to library where custom decorators might need to be configured. Seems to be a fairly consistent ask for these rules

**Comment by elliotaplant** [comment]
We ended up solving this by making the routes that return paginated DTOs extend an API decorated base `PageDto`. Contrary to my initial post, I think that creating decorators like `ApiPaginatedResponse` may actually be an anti-pattern because it duplicates the responsibility of type annotations on network DTOs. 

For example, routes decorated by `@ApiPaginatedResponse(SomeDataType)` would have to decorate methods that return a value of `PageDto<SomeDataType>`. Both `ApiPaginatedResponse` and `PageDto` would have to provide the same information to Swagger, which invites an opportunity to have contradicting information. Better to let `PageDto` be the source of truth and simply use `@ApiOkResponse({ type: PageDto })`.

What other asks have you seen for custom rules? I'm curious to see if they might fall into the same pattern we saw in our project.

**Comment by darraghoriordan** [comment]
Hey yea that sounds like a nice solution with the object properties handling it

This link is an example of a rule has a configuration option for telling the rule a list of custom "class-validator" decorators. But this is a very common use case where people create custom validators or combine multiple validators into one for their domain.

https://github.dev/darraghoriordan/eslint-plugin-nestjs-typed/blob/1533ee31981e0a2c0992845d704eaa6a09516fd5/src/rules/validateNonPrimitvesNeedsTypeDecorator/validateNonPrimitiveNeedsDecorators.ts#L45

i will close this issue, it sounds like it's resolved 👍

**Comment by Tsugami** [comment]
> Hey yea that sounds like a nice solution with the object properties handling it
> 
> This link is an example of a rule has a configuration option for telling the rule a list of custom "class-validator" decorators. But this is a very common use case where people create custom validators or combine multiple validators into one for their domain.
> 
> https://github.dev/darraghoriordan/eslint-plugin-nestjs-typed/blob/1533ee31981e0a2c0992845d704eaa6a09516fd5/src/rules/validateNonPrimitvesNeedsTypeDecorator/validateNonPrimitiveNeedsDecorators.ts#L45
> 
> i will close this issue, it sounds like it's resolved 👍

This not works for me, there are different rules

Error:
![image](https://github.com/darraghoriordan/eslint-plugin-nestjs-typed/assets/27602189/bd684863-3adc-4513-bb70-b1bd9cb04ddf)

Eslint config:
![image](https://github.com/darraghoriordan/eslint-plugin-nestjs-typed/assets/27602189/a1ad8143-f2b6-4010-8582-fd0fb2d6d237)

ApiPaginatedResponse is my custom decorator
