### ISSUE TITLE
Add a rule to sort `controllers`, `providers` and `imports/exports` in module alphabetically

### ISSUE THREAD

**Issue by imranbarbhuiya** [darraghoriordan/eslint-plugin-nestjs-typed#58]
ref: https://github.com/angular-eslint/angular-eslint/blob/main/packages/eslint-plugin/docs/rules/sort-ngmodule-metadata-arrays.md

**Comment by imranbarbhuiya** [comment]
yes but it's diff than what I want. I'm talking about these `imports`, `exports`, 

```ts
@Module({
	imports: [ServersModule, MongoStatsModule],
	controllers: [ServersController],
	providers: [ServersService, MongoStatsService],
})
export class ServersModule {}
```

**Comment by darraghoriordan** [comment]
ahh right. gotcha

**Comment by darraghoriordan** [comment]
I added this. it's in the latest version. i ran it on one of my projects and it seems to work as expected. 

It's not in default config, you'll have to turn it on.

Docs are here: https://github.com/darraghoriordan/eslint-plugin-nestjs-typed/blob/main/src/docs/rules/sort-module-metadata-arrays.md

**Comment by imranbarbhuiya** [comment]
Hi @darraghoriordan, Array sorting works for most of the files but sometimes it needs multiple runs to sort. It sorts one by one ig. Example of such `Module`

```ts
@Module({
	imports: [
		ServeStaticModule.forRoot({
			rootPath: join(__dirname, '..', 'public'),
			serveStaticOptions: {
				index: false,
				fallthrough: false,
			},
		}),
		ConfigModule.forRoot({
			isGlobal: true,
			envFilePath: '.env',
		}),
		MongooseModule.forRoot(process.env.DB_URI, {
			connectionName: 'sofi',
			connectionFactory: (connection: Connection) => {
				connection.on('connected', () => {
					logger.log('Sofi DB connected');
				});
				connection.on('disconnected', () => {
					logger.log('Sofi DB disconnected');
				});
				connection.on('error', (error) => {
					logger.log(`Sofi DB connection failed! Error: ${error}`);
				});

				logger.log(`Sofi DB ${STATES[connection.readyState]}`);
				return connection;
			},
		}),
		MongooseModule.forRoot(process.env.PROFILE_DB_URI, {
			connectionName: 'profile',
			connectionFactory: (connection: Connection) => {
				connection.on('connected', () => {
					logger.log('Profile DB connected');
				});
				connection.on('disconnected', () => {
					logger.log('Profile DB disconnected');
				});
				connection.on('error', (error) => {
					logger.log(`Profile DB connection failed! Error: ${error}`);
				});

				logger.log(`Profile DB ${STATES[connection.readyState]}`);
				return connection;
			},
		}),
		AlbumModule,
		ArtModule,
		AuthModule,
		BackgroundModule,
		CharacterModule,
		CommentModule,
		EventModule,
		FrameModule,
		GlowModule,
		ItemModule,
		LikesModule,
		MemberModule,
		PostModule,
		PriceModule,
		ProfileModule,
		ServersModule,
		SpawnModule,
		SusModule,
		UserModule,
	],
	controllers: [],
	providers: [],
})
export class AppModule {
```

also, the error message only says 
> `Module` metadata arrays should be sorted in ASC alphabetical order

but it doesn't say about which prop

**Comment by imranbarbhuiya** [comment]
similar issue https://github.com/angular-eslint/angular-eslint/issues/1232
and fix pr https://github.com/angular-eslint/angular-eslint/pull/1303

**Comment by darraghoriordan** [comment]
hey, thanks for testing it out. Yea I mentioned the issue with only fixing one item at a time in the docs. I agree its a bit annoying the first time you turn on the rule, but after that most additions to the list would be one-by-one. 

Assuming someone lints in their IDE it should be ok.

I don't have any more time to spend on this but will happily accept PRs for those improvements. They would be awesome additions for all users of the plugin 👍
