### ISSUE TITLE
rules should be consistently named in plural or singular form

### ISSUE THREAD

**Issue by CodingSpiderFox** [darraghoriordan/eslint-plugin-nestjs-typed#60]
Some rules from this plugin are named in singular:

* api-method-should-specify-api-response

while others are named in plural

* api-methods-should-be-guarded

this is a bit misleading when configuring the rule severity in the eslintrc 
I was trying "api-methods-should-specify-api-response" instead of the singular form

**Comment by darraghoriordan** [comment]
Hey, thanks for raising this. it's noted and i'll look out for this in PRs in the future.  

Changing the rule names now will break people's existing configuration so I'm reluctant to change them. 

Let me know if the documentation is wrong though. That is easy to fix.

**Comment by CodingSpiderFox** [comment]
yes, that would be a problem. Would it be possible to alias the rules somehow?
