### ISSUE TITLE
Rule to detect that an injected dependency has no @Injectable() decorator on the defining class

### ISSUE THREAD

**Issue by CodingSpiderFox** [darraghoriordan/eslint-plugin-nestjs-typed#67]
Consider the following classes

```
@Injectable()
export class MyClassA {
  constructor(private readonly myInstaceB : MyClassB) {}

  //[...] implementation
}
```

```
export class MyClassB {

  //[...] implementation
}
```

Note that class B is not injectable.
In the constructor line in class A, I want the eslint check to highlight that the myInstanceB cannot be instantiated because MyClassB is not injectable

**Comment by micalevisk** [comment]
actually, that code works as expected.

`MyClassA` is marked as a injectable. So `MyClassA` can inject things. It is not the other away around.

We don't have to add the `@Injectable()` to a class unless we want to inject something in that class. Or unless that class is using the `@Inject()` paramter decorator.

**Comment by micalevisk** [comment]
if you don't believe me :p

![image](https://github.com/darraghoriordan/eslint-plugin-nestjs-typed/assets/13461315/261b40a5-9fd7-4a43-869a-8f781011061b)

**Comment by micalevisk** [comment]
@darraghoriordan I think you can close this :)
