### ISSUE TITLE
Support for @typescript-eslint/parse v6

### ISSUE THREAD

**Issue by lucavb** [darraghoriordan/eslint-plugin-nestjs-typed#71]
Since I didn't see any issues regarding this yet :) 

@typescript-eslint/parser was released recently https://github.com/typescript-eslint/typescript-eslint/releases/tag/v6.0.0 and I guess we are not the only ones that would like to upgrade (at least our renovate would like to 😅). Currently the `peerDependency` mentioned [here](https://github.com/darraghoriordan/eslint-plugin-nestjs-typed/blob/main/package.json#L80) is preventing us from upgrading while using this package. I haven't tested whether this requires any code changes to this package. 

Besides that, thanks for the package :)

**Comment by sab-valari** [comment]
+1

**Comment by darraghoriordan** [comment]
done in v4.0

**Comment by darraghoriordan** [comment]
ah it took so many changes to make the plugin work with tseslint 6 i missed the peer deep.

fixed  in v4.0.2

thanks for letting me know
